---
- name: Getting the server app
  unarchive:
    src: https://minecraft.azureedge.net/bin-linux/bedrock-server-1.12.1.1.zip
    dest: "{{ minecraft_install_folder }}"
    creates: "{{ minecraft_install_folder }}/bedrock_server"
    remote_src: yes
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating server config file
  template:
    src: server.properties
    dest: "{{ minecraft_install_folder }}/server.properties"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating white list file
  template:
    src: whitelist.json.j2
    dest: "{{ minecraft_install_folder }}/whitelist.json"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  when: minecraft_white_list
  notify:
    - restart minecraft-server

- name: Creating user permissions file
  template:
    src: permissions.json.j2
    dest: "{{ minecraft_install_folder }}/permissions.json"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  when: minecraft_white_list
  notify:
    - restart minecraft-server

- name: Creating service file
  template:
    src: minecraft.service
    dest: "/etc/systemd/system/{{ minecraft_service_name }}.service"
    owner: "root"
    group: "root"
  become: true
  notify:
    - restart minecraft-server
