---
- name: Install dependencies
  apt:
    name:
      - openjdk-8-jdk
    state: present
    update_cache: true
  become: true

- name: Getting the server app
  get_url:
    url: https://launcher.mojang.com/v1/objects/3dc3d84a581f14691199cf6831b71ed1296a9fdf/server.jar
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating white list file
  template:
    src: whitelist.json.j2
    dest: "{{ minecraft_install_folder }}/whitelist.json"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  when: minecraft_white_list
  notify:
    - restart minecraft-server

- name: Creating user permissions file
  template:
    src: ops.json.j2
    dest: "{{ minecraft_install_folder }}/ops.json"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  when: minecraft_white_list
  notify:
    - restart minecraft-server

- name: Prepare the eula.txt file
  lineinfile:
    dest: "{{ minecraft_install_folder }}/eula.txt"
    line: "eula=true"
    create: true
    state: present
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating startup script
  template:
    src: start_server.sh
    dest: "{{ minecraft_install_folder }}/start_server.sh"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating service file
  template:
    src: minecraft_java.service
    dest: "/etc/systemd/system/{{ minecraft_service_name }}.service"
    owner: "root"
    group: "root"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server
