---
- name: Install dependencies
  apt:
    name:
      - openjdk-8-jdk
    state: present
    update_cache: true
  become: true

- name: Get list of available Minecraft builds
  uri:
    url: "https://launchermeta.mojang.com/mc/game/version_manifest.json"
  register: minecraft_vers_list

- name: Search builds for latest version and get build info url
  set_fact: 
    minecraft_version_url: "{{ minecraft_vers_list.json | json_query(query)  }}"
  vars:
    # Query to look up the latest release of minecraft
    query: "versions[?id=='{{ minecraft_vers_list.json.latest.release }}'].url"
  when: minecraft_java_version == "latest"

- name: Search builds for specified version and get build info url
  set_fact: 
    minecraft_version_url: "{{ minecraft_vers_list.json | json_query(query)  }}"
  vars:
    # Query to look up the minecraft version we specified from the list
    query: "versions[?id=='{{ minecraft_java_version }}'].url"
  when: minecraft_java_version != "latest"

- name: Get Minecraft download url from build info
  uri:
    url: "{{ minecraft_version_url[0] }}"
  register: minecraft_version_info

- name: Set Minecraft server download url
  set_fact: 
    minecraft_download_url: "{{ minecraft_version_info.json.downloads.server.url }}"

- name: Getting the server app
  get_url:
    url: "{{ minecraft_download_url }}"
    dest: "{{ minecraft_install_folder }}"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating white list file
  template:
    src: whitelist.json.j2
    dest: "{{ minecraft_install_folder }}/whitelist.json"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  when: minecraft_white_list
  notify:
    - restart minecraft-server

- name: Creating user permissions file
  template:
    src: ops.json.j2
    dest: "{{ minecraft_install_folder }}/ops.json"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  when: minecraft_white_list
  notify:
    - restart minecraft-server

- name: Creating user permissions file
  template:
    src: server_java.properties
    dest: "{{ minecraft_install_folder }}/server.properties"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Prepare the eula.txt file
  lineinfile:
    dest: "{{ minecraft_install_folder }}/eula.txt"
    line: "eula=true"
    create: true
    state: present
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating startup script
  template:
    src: start_server.sh
    dest: "{{ minecraft_install_folder }}/start_server.sh"
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server

- name: Creating service file
  template:
    src: minecraft_java.service
    dest: "/etc/systemd/system/{{ minecraft_service_name }}.service"
    owner: "root"
    group: "root"
    mode: 0755
  become: true
  notify:
    - restart minecraft-server
