---
- name: Install dependencies
  apt:
    name:
      - git
      - wget
      - curl
      - unzip
    state: present
    update_cache: true
  become: true

- name: Create service user
  user:
    name: "{{ app_service_user }}"
    system: true
    state: present
  become: true

- name: Create service folder
  file:
    path: "{{ minecraft_install_folder }}"
    state: directory
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: true

- name: Install bedrock version
  include_tasks: tasks/bedrock.yml
  when: minecraft_server_option == 'bedrock'

- name: Install java version
  include_tasks: tasks/java.yml
  when: minecraft_server_option == 'java'
