---
# tasks file for minecraft-ansible-role
- name: Install dependencies
  apt:
    name:
#      - openjdk-8-jdk
      - git
      - wget
      - curl
      - unzip

    state: present
    update_cache: true

- name: Create service user
  user:
    name: "{{ app_service_user }}"
    system: true
    state: present

- name: Create service folder
  file:
    path: "{{ minecraft_install_folder }}"
    state: directory
    owner: "{{ app_service_user }}"
    group: "{{ app_service_user }}"
    mode: 0755
  become: yes

- name: Getting the server app
  unarchive:
    src: https://minecraft.azureedge.net/bin-linux/bedrock-server-1.12.1.1.zip
    dest: "{{ minecraft_install_folder }}"
    creates: "{{ minecraft_install_folder }}/bedrock_server"
    remote_src: yes
    mode: 0755
  become: yes
